# Generated by Django 2.1 on 2019-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.IntegerField(help_text='Key of qualification', primary_key=True, serialize=False, unique=True)),
                ('subfield_of_study_id', models.IntegerField()),
                ('qualification_id', models.IntegerField()),
                ('saqa_id', models.IntegerField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=255)),
                ('NQF_level', models.IntegerField()),
                ('duration_in_months', models.IntegerField()),
                ('full_time', models.BooleanField()),
                ('part_time', models.BooleanField()),
                ('credits_after_completion', models.IntegerField()),
                ('distance_learning', models.BooleanField()),
                ('estimated_annual_fee', models.IntegerField()),
                ('campus_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QualificationEntranceRequirementSubjects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('qualification_id', models.CharField(max_length=255)),
                ('subject_id', models.CharField(max_length=255)),
                ('minimum_score', models.IntegerField()),
                ('required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification_id', models.IntegerField()),
                ('assessment', models.BooleanField()),
                ('interview', models.BooleanField()),
                ('admission_point_score', models.IntegerField()),
                ('min_qualification', models.IntegerField()),
            ],
        ),
    ]
