# Generated by Django 2.1 on 2019-01-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('provider_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccupationQualification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('occupation_id', models.IntegerField()),
                ('qualitication_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('logo_url', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('admissions_contact_no', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.IntegerField()),
                ('module_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryInstitutionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryInstitutionTypeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('secondary_institution_type_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubFieldOfStudy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('field_of_study_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubFieldOfStudyOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_field_of_study_d', models.IntegerField()),
                ('occupation_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='QualificationEntranceRequirementSubjects',
            new_name='QualificationEntranceRequirementSubject',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='saqa_id',
            field=models.IntegerField(),
        ),
    ]
