# Generated by Django 2.1 on 2019-01-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0002_auto_20190118_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='NQF_level',
            new_name='nqf_level',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='qualification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ford3.Qualification'),
        ),
    ]
