# Generated by Django 2.1 on 2019-01-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0003_auto_20190118_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OccupationQualification',
        ),
        migrations.DeleteModel(
            name='QualificationModule',
        ),
        migrations.DeleteModel(
            name='SecondaryInstitutionTypeSubject',
        ),
        migrations.DeleteModel(
            name='SubFieldOfStudyOccupation',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='subfield_of_study_id',
        ),
        migrations.AddField(
            model_name='qualification',
            name='modules',
            field=models.ManyToManyField(to='ford3.Module'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='occupation_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ford3.Occupation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='sub_field_of_study_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ford3.SubFieldOfStudy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='subjects',
            field=models.ManyToManyField(through='ford3.QualificationEntranceRequirementSubject', to='ford3.Subject'),
        ),
        migrations.AddField(
            model_name='subfieldofstudy',
            name='occupation_id',
            field=models.ManyToManyField(to='ford3.Occupation'),
        ),
        migrations.AddField(
            model_name='subject',
            name='secondary_institution_types',
            field=models.ManyToManyField(to='ford3.SecondaryInstitutionType'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ford3.Provider'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='campus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.Campus'),
        ),
        migrations.AlterField(
            model_name='qualificationentrancerequirementsubject',
            name='qualification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.Qualification'),
        ),
        migrations.AlterField(
            model_name='qualificationentrancerequirementsubject',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.Subject'),
        ),
        migrations.AlterField(
            model_name='subfieldofstudy',
            name='field_of_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.FieldOfStudy'),
        ),
    ]
