# Generated by Django 2.1 on 2019-01-21 08:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0004_auto_20190118_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The spatial point position of the campus', null=True, srid=4326),
        ),
    ]
