# Generated by Django 2.1 on 2019-01-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0005_campus_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='location',
        ),
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
