# Generated by Django 2.1.7 on 2019-03-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0016_merge_20190322_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='physical_address_postal_code',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
