# Generated by Django 2.1.7 on 2019-03-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0026_auto_20190328_0940'),
        ('ford3', '0026_saqaqualification'),
    ]

    operations = [
    ]
