# Generated by Django 2.1.7 on 2019-03-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0026_saqaqualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='nqf_level',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='saqa_id',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='sub_field_of_study',
        ),
        migrations.AddField(
            model_name='qualification',
            name='saqa_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ford3.SAQAQualification'),
        ),
        migrations.AddField(
            model_name='saqaqualification',
            name='sub_field_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ford3.SubFieldOfStudy'),
        ),
    ]
