# Generated by Django 2.1.7 on 2019-03-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0027_merge_20190327_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ford3.Campus'),
        ),
    ]
