# Generated by Django 2.1.7 on 2019-04-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0031_merge_20190328_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_logo',
            field=models.ImageField(blank=True, upload_to='provider_logo'),
        ),
    ]
