# Generated by Django 2.1.7 on 2019-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0031_merge_20190328_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_logo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo'),
        ),
    ]
