# Generated by Django 2.1.7 on 2019-04-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0032_auto_20190414_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='physical_postal_code',
            new_name='physical_address_postal_code',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='postal_postal_code',
            new_name='postal_address_postal_code',
        ),
    ]
