# Generated by Django 2.1.7 on 2019-04-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0035_auto_20190426_1743'),
        ('ford3', '0035_prospect'),
        ('ford3', '0034_merge_20190416_2147'),
    ]

    operations = [
    ]
