# Generated by Django 2.1.7 on 2019-04-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0036_merge_20190430_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(help_text='Prospect email address', max_length=254, verbose_name='Email (required)'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='name',
            field=models.CharField(help_text='Prospect first and last name', max_length=150, verbose_name='Name (required)'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='telephone',
            field=models.CharField(blank=True, help_text='Prospect telephone number', max_length=150),
        ),
    ]
