# Generated by Django 2.1.7 on 2019-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0041_merge_20190507_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='saqaqualification',
            name='name',
            field=models.CharField(help_text='The name of the qualification as approved by SAQA', max_length=255, null=True),
        ),
    ]
