# Generated by Django 2.1.7 on 2019-05-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0042_auto_20190514_1619'),
        ('ford3', '0043_auto_20190516_1312'),
    ]

    operations = [
    ]
