# Generated by Django 2.1.7 on 2019-05-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0044_merge_20190517_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Qualification has been deleted'),
        ),
        migrations.AlterField(
            model_name='saqaqualification',
            name='field_of_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ford3.FieldOfStudy'),
        ),
    ]
