# Generated by Django 2.1.7 on 2019-05-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0045_auto_20190517_1444'),
        ('ford3', '0045_campusevent_deleted'),
    ]

    operations = [
    ]
