# Generated by Django 2.1.7 on 2019-05-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0046_merge_20190520_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Qualification has been deleted'),
        ),
    ]
