# Generated by Django 2.1.7 on 2019-05-24 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ford3', '0047_provider_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderUsersCampusUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campus_user_id', to=settings.AUTH_USER_MODEL)),
                ('provider_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the province', max_length=255)),
                ('location', models.CharField(help_text="The province's location", max_length=255, null=True)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
