# Generated by Django 2.1.7 on 2019-05-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0048_provideruserscampususers_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ford3.Province'),
        ),
    ]
